# Site settings
title: Tumeo Space
description: >
  Systems Analyst and Game Developer at Novastrike;␊
  Supporter of free software initiative;␊
  FLOSS, Python, Ren'Py and Godot Engine;␊
  Dyslexic but learning English and 日本語;␊

baseurl: 
url: "https://tumeo.space"
# User settings
username: tumeo
user_title: William Tumeo - Game Developer
email: contact@tumeo.space
twitter_username: tumeo_
github_username: williamd1k0
gitlab_username: tumeo
itch_username: tumeo
mastodon_instance_username: mastodon.social/@tumeo
misskey_instance_username: misskey.dev/@tumeo
creary_username: tumeo
matrix_username: "@tumeo:matrix.org"
odysee_username: "tumeo:c"
sessionapp_id: "05c8728266e1ce5a789e888ca391e75b43fa1802553ec63c1b89eebc41b6a7b922"
profile_picture: /assets/img/site/profile.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

comments_enabled: true
ads_enabled: true

timezone: America/Sao_Paulo

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: about me
    url: /about
  - title: posts
    url: /posts
  - title: tags
    url: /tags
  - title: donations
    url: /donations

# projects in header index
projects:
  - name: MANGA Plus Top 40
    url: https://manga.tumeo.space
  - name: PixelStyle
    url: https://github.com/williamd1k0/PixelStyle
  - name: Untitled Glue Game
    url: https://pigdev.itch.io/untitled-glue-game
  - name: GDScript Playground
    url: https://gd.tumeo.space/
  - name: Kagayaki no Neiro
    url: https://tumeo.itch.io/kagayaki-no-neiro
  - name: Ren'Py Package for Atom
    url: https://github.com/renpy/language-renpy
  - name: Monster Hunter Pocket
    url: https://tumeo.itch.io/monster-hunter-pocket
  - name: Burnt
    url: https://tumeo.itch.io/burnt
  - name: Godot Sandbox
    url: https://github.com/williamd1k0/godot-sandbox
  - name: Plue's Adventures 2
    url: https://github.com/williamd1k0/plues-adventures-2
  - name: gdscript-cli
    url: https://github.com/williamd1k0/gdscript-cli
  - name: redmask
    url: https://github.com/williamd1k0/redmask
  - name: Godot Pong EX
    url: https://github.com/williamd1k0/godot-pong-ex

include:
  - .well-known
# exclude my node related stuff
exclude:
  - package.json
  - gulpfile.js
  - src
  - node_modules
  - Makefile
  - README.md
